// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"KurtsAnimationPlugin","status":true,"description":"v1.0.0 Allows different number of frames for each character animation using JSON frame data","parameters":{"Idle Up Speed":"f * 0.5","Idle Down Speed":"f * 0.5","Idle Left Speed":"f * 0.5","Idle Right Speed":"f * 0.5","Walk Up Speed":"f * 0.5","Walk Down Speed":"f * 0.5","Walk Left Speed":"f * 0.4","Walk Right Speed":"f * 0.4","Run Up Speed":"f * 0.8","Run Down Speed":"f * 0.8","Run Left Speed":"f * 0.8","Run Right Speed":"f * 0.8","Run Speed Threshold":"6"}},
{"name":"KurtsPerpectivePlugin","status":true,"description":"v1.0.0 Adds 2.5D perspective effect by scaling characters based on Y position","parameters":{"Min Scale":"0.88","Max Scale":"1.03","Control Point Y":"60.0","Control Point Scale":"0.88","Use Screen Based":"false"}},
{"name":"KurtsKeyMapper","status":true,"description":"v1.0.0 Customizable keyboard controls for action and movement","parameters":{"Action Button":"e","Movement Keys":"wasd"}},
{"name":"KurtsInteractionRangePlugin","status":true,"description":"v2.1.0 Expands event interaction area with directional ranges","parameters":{"Enable Debug":"true","Icon Image":"interact","Icon Offset Y":"20","Interaction Origin %":"40"}},
{"name":"KurtsShakePlugin","status":true,"description":"v1.0.0 Shake the player sprite only (no camera shake)","parameters":{}},
{"name":"KurtsMouseWheelZoom","status":true,"description":"v1.0.0 Mouse wheel zoom in/out for map camera","parameters":{"Min Zoom":"0.50","Max Zoom":"3.00","Zoom Step":"0.10","Smoothness":"0.20","Disable During Events":"true"}},
{"name":"KurtsCameraLag","status":true,"description":"v1.0.0 Adds smooth camera lag/easing when following the player","parameters":{"Lag Strength":"0.03","Horizontal Lag":"0.03","Vertical Lag":"0.03"}}
];
