// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"GALV_CharacterFrames","status":false,"description":"v.1.4 Enables map character sheets to have more frames per character.","parameters":{"Frame Speed Modifier":"f * 0.6","fileSymbol":"%"}},
{"name":"GALV_MessageStyles","status":false,"description":"(v.2.8) Settings to change how your \"Show Text\" messages look as well as code to make them floating.","parameters":{"Input Indicator":"2,0,-12","Indicator Zoom":"100","Message Padding":"0,0,0,0","Message Windowskin":"Window","Other Windowskins":"Window1,Window2,Window3","Arrow Graphic":"WindowArrow","Other Arrow Graphics":"WindowArrow1,WindowArrow2,WindowArrow3","Windowskin Back Opacity":"192","Y Offset":"60","Font":"","Font Filename":"","Font Outline":"true","Font Size":"28"}},
{"name":"JSONFrameAnimations","status":true,"description":"v1.0.0 Allows different number of frames for each character animation using JSON frame data","parameters":{"Idle Up Speed":"f * 0.5","Idle Down Speed":"f * 0.5","Idle Left Speed":"f * 0.5","Idle Right Speed":"f * 0.5","Walk Up Speed":"f * 0.6","Walk Down Speed":"f * 0.6","Walk Left Speed":"f * 0.6","Walk Right Speed":"f * 0.6","Run Up Speed":"f * 1.0","Run Down Speed":"f * 1.0","Run Left Speed":"f * 1.0","Run Right Speed":"f * 1.0","Run Speed Threshold":"6"}}
];
