// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"KurtsAnimationPlugin","status":true,"description":"v1.0.1 Allows different number of frames for each character animation using JSON frame data","parameters":{"Idle Up Speed":"f * 0.06","Idle Down Speed":"f * 0.06","Idle Left Speed":"f * 0.06","Idle Right Speed":"f * 0.06","Walk Up Speed":"f * 0.3","Walk Down Speed":"f * 0.3","Walk Left Speed":"f * 0.3","Walk Right Speed":"f * 0.3","Run Up Speed":"f * 0.2","Run Down Speed":"f * 0.2","Run Left Speed":"f * 0.2","Run Right Speed":"f * 0.2","Run Speed Threshold":"5","Enable Debug":"false","Static Dollar Characters":"$dressRed"}},
{"name":"KurtsPerpectivePlugin","status":false,"description":"v1.0.0 Adds 2.5D perspective effect by scaling characters based on Y position","parameters":{"Min Scale":"0.88","Max Scale":"1.10","Control Point Y":"60.0","Control Point Scale":"0.88","Use Screen Based":"false"}},
{"name":"KurtsKeyMapper","status":true,"description":"v1.0.0 Customizable keyboard controls for action and movement","parameters":{"Action Button":"e","Movement Keys":"wasd"}},
{"name":"KurtsInteractionRangePlugin","status":true,"description":"v2.1.0 Expands event interaction area with directional ranges","parameters":{"Enable Debug":"true","Icon Image":"interact","Icon Offset Y":"20","Interaction Origin %":"40"}},
{"name":"KurtsShakePlugin","status":true,"description":"v1.0.0 Shake the player sprite only (no camera shake)","parameters":{}},
{"name":"KurtsMouseWheelZoom","status":true,"description":"v1.4.0 Mouse wheel zoom in/out for map camera (resolution-adaptive)","parameters":{"Min Zoom":"0.33","Max Zoom":"3.00","Zoom Step":"0.10","Smoothness":"0.20","Disable During Events":"true","Disable During Message":"true"}},
{"name":"KurtsCameraLag","status":true,"description":"v1.0.0 Adds smooth camera lag/easing when following the player","parameters":{"Lag Strength":"0.06","Horizontal Lag":"0.06","Vertical Lag":"0.06","Center Zoom Threshold":"0.60","Player Y Offset":"100","Transition Lag":"0.03"}},
{"name":"KurtsMapForeground","status":true,"description":"v1.1.0 Displays pictures as foreground layers anchored to the map","parameters":{"Offset X":"-24","Offset Y":"0"}},
{"name":"KurtsFPSLogger","status":true,"description":"v1.0.0 Logs FPS to console once per second","parameters":{"Enabled":"true"}},
{"name":"KurtsOptionsMenu","status":true,"description":"v1.0.0 Custom options menu with display, performance, camera & controls","parameters":{}},
{"name":"KurtsTranslationTooltip","status":true,"description":"v1.3.0 Hoverable translation tooltips in message text","parameters":{"Box Image":"translationBox","Tooltip Font Size":"20","Foreign Text Color":"#FFD700","Tooltip Offset Y":"0"}},
{"name":"KurtsPlayerDefaults","status":true,"description":"Sets default player speed, frequency, and facing direction on map load.","parameters":{"Move Speed":"4","Move Frequency":"5","Facing Direction":"8","Through":"false"}},
{"name":"KurtsResolutionPictures","status":true,"description":"v1.4.4 Resolution-adaptive pictures & message windows","parameters":{"Reference Width":"1280","Reference Height":"720"}}
];
